config/routes.rb
Rails.application.routes.draw do
  root "trips#index"
  
  devise_for :users 

  resources :trips do
    resources :locations 
  end
  
  resources :locations do
    resources :addresses
  end


  
  
    

  


end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :location
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :trip

  has_many :addresses, dependent: :destroy
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :locations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :trips
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]
  
  def index
    @location = Location.find(params[:location_id])
    @addresses = @location.addresses
  end

  def show
    # @location = Location.find(params[:location_id])
    # @address = @location.addresses.find(params[:id])
  end

  def new
    @location = Location.find(params[:location_id])
    @address = @location.addresses.new
    render partial: "form"
  end

  def create
    @location = Location.find(params[:location_id])
    @address = @location.addresses.new(address_params)
    
    if @address.save
      redirect_to location_addresses_path
    else 
      render :new
    end
  end

  def edit
    # @location = Location.find(params[:location_id])
    # @address = @location.addresses.find(params[:id])

    render partial: "form"
  end

  def update
    # @location = Location.find(params[:sub_id])
    # @address = @location.addresses.find(params[:id])

    if @address.update(address_params)
      redirect_to location_path(@location)
    else
      render partial :edit
    end
  end

  def destroy
    @location = Location.find(params[:location_id])
    address = @location.addresses.find(params[:id])
    address.destroy
    redirect_to location_path(@location)
  end
  
 

  private

  def address_params
    params.require(:address).permit(:address, :city, :state, :zip)
  end

  def set_address
    @address = Address.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
 before_action :set_location, only: [:show, :edit, :update, :destroy]
#  before_action :find_trip

  def index
    @trip = Trip.find(params[:trip_id])
    @locations = @trip.locations
    # @locations = @location_trip.locations
  end

  def show
  end

  def new
    @trip = Trip.find(params[:trip_id])
    @location = @trip.locations.new
    # @location = @location_trip.locations.new
    render partial: "form" ##form for locations
  end

  def create

    @trip = Trip.find(params[:trip_id])
    @location = @trip.locations.new(location_params)
    
    if @location.save
      redirect_to trip_locations_path
    else 
      render :new
    # @location = @location_trip.locations.new(location_params)
  
    # if @location.save
    #   redirect_to trip_locations_path
    # else
    #   render :new
    end
  
  end 



  def edit
   render partial: "form"
  end

  def update
    if @location.update(location_params)
      redirect_to locations_path(@location)
    else
      render :edit
    end

  end

  def destroy
    # @trip = Trip.find(params[:trip_id])
    # location = @trip.locations.find(params[:id])
    location.destroy
    redirect_to trip_locations_path(@location)

  end

 


  private

  def location_params
params.require(:location).permit(:name, :trip_id)
  end

  def set_location
    @location = Location.find(params[:id])
  end

  # def find_trip
  #   @location_trip = current_user.trips.find(params[:trip_id])
  # end


end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  def index
    @trips = current_user.trips
  end

  def show

  end

  def new
    @trip = Trip.new
    render partial:"form"
  end

  def edit
    render partial:"form"
  end

  def update
    if @trip.update(trip_params)
      redirect_to trips_path(@trip)
    else
      render :edit
    end

  end

  def create 
    @trip = current_user.trips.new(trip_params)
      if @trip.save
        redirect_to trips_path
      else
        render :new
      end

  end

  def destroy 
    set_trip.destroy
    redirect_to trips_path

  end


  private 

  def trip_params
    params.require(:trip).permit(:name)
  end

  def set_trip
    @trip = current_user.trips.find(params[:id])
  end


end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/addresses/_form.html.erb
<h1><%= @address.id ? 'Edit Address' : 'Create Address' %></h1>
<hr />
<%= form_for [@trip, @location, @address] do |f| %>
  <%= f.label :address %>
  <%= f.text_field :address, required: true, autofocus: true %>
  <%= f.label :city %>
  <%= f.text_field :city, required: true, autofocus: true %>
  <%= f.label :state %>
  <%= f.text_field :state, required: true, autofocus: true %>
  <%= f.label :zip %>
  <%= f.text_field :zip, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/addresses/edit.html.erb
<h1>Addresses#edit</h1>
<p>Find me in app/views/addresses/edit.html.erb</p>

app/views/addresses/index.html.erb
<h1>Addresses#index</h1>
<%= link_to 'Create a new address', location_addresses_path%>

 <ol>
  <% @addresses.each do |address| %>
    <li><%= link_to address_path, address %></li>
  <% end %>
</ol>

app/views/addresses/new.html.erb
<h1>Addresses#new</h1>
<p>Find me in app/views/addresses/new.html.erb</p>

app/views/addresses/show.html.erb
<h1>Addresses#show</h1>
<p>Hello</p>

app/views/layouts/_navbar.html.erb
<nav class="ui menu">
  <div class="right menu">
    <% if current_user %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "item" %>
    <% else %>
      <%= link_to "Register", new_user_registration_path, class: "item" %>
      <%= link_to "Login", new_user_session_path, class: "item" %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TripTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/navbar"%>
    <div class='ui container'>
      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<h1><%= @location.id ? 'Edit Location' : 'Create Location' %></h1>
<hr />
<%= form_for [@trip, @location] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/locations/edit.html.erb
<h1>Locations#edit</h1>
<p>Find me in app/views/locations/edit.html.erb</p>

app/views/locations/index.html.erb
<h1>Locations!</h1>
<%= link_to 'Create Location', new_trip_location_path(@trip) %>

<ol>
  <% @locations.each do |location| %>
    <li><%= link_to location.name, location %></li>
  <% end %>
<ol>

app/views/locations/new.html.erb
<h1>Locations#new</h1>
<p>Find me in app/views/locations/new.html.erb</p>

app/views/locations/show.html.erb
<h1><%= @location.name %></h1>
<br />




<br/>
<%=link_to "Add Address", new_location_address_path(@location)%>
<br/>
<%= link_to "Back", trip_locations_path(@location)%>
<br/>
<%= link_to "Edit address", edit_location_address_path(@location)%>
<br/>
<%= link_to "Delete address", @location, method: :delete%>
<br/>

# // this is where we need to link down to each location's address

app/views/trips/_form.html.erb
<h1><%= @trip.id ? 'Edit trip' : 'Create trip' %></h1>
<hr />
<%= form_for @trip do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/trips/edit.html.erb
<h1>Trips#edit</h1>
<p>Find me in app/views/trips/edit.html.erb</p>

app/views/trips/index.html.erb
<h1>Trips</h1>

<%= link_to 'Create Trip', new_trip_path %>

<ol>
  <% @trips.each do |trip| %>
    <li><%= link_to trip.name, trip %></li>
  <% end %>
<ol>

app/views/trips/new.html.erb
<h1>Trips#new</h1>
<p>Find me in app/views/trips/new.html.erb</p>

app/views/trips/show.html.erb
<h1><%= @trip.name %></h1>
<hr />
<p> Select a location (or option below) </p>
<br/>

<ol>
  <% @trip.locations.each do |location| %>
    <li><%= link_to location.name, location %></li>
  <% end %>
</ol>
<br/>
<%=link_to "Add location", new_trip_location_path(@trip)%>
<br/>
<%= link_to "Back", trips_path(@trip)%>
<br/>
<%= link_to "Edit trip", edit_trip_path(@trip)%>
<br/>
<%= link_to "Delete trip", @trip, method: :delete%>
<br/>